### ISSUE TITLE
query variable in sosl and soql nodes has wrong scope

### ISSUE THREAD

**Issue by dwindibank** [Stwissel/node-red-contrib-salesforce#13]
The query variable (var query ='') in the soql and sosl nodes have the wrong scope. This results in the variable being reused ... i.e. multiple message's overwriting the value of the variable (via each messages' msg.query value).  

I think this may have been the root cause on jeffdonthemic/node-red-contrib-salesforce#8 and jeffdonthemic/node-red-contrib-salesforce#2

**Comment by dwindibank** [comment]
I created a pull request for this:  #14

**Comment by Stwissel** [comment]
Thx for that. Slipped my debugging. Merged in

**Comment by Stwissel** [comment]
Btw.: need to bump version in package.json, so build process can automatically publish it

**Comment by dwindibank** [comment]
Awesome. Thanks!

I'll remember about the version bump for next time I submit a pull request. Thanks, again.
