### ISSUE TITLE
soql and sosl nodes connection errors are caught by the Catch All node but not query errors (dml node too)

### ISSUE THREAD

**Issue by dwindibank** [Stwissel/node-red-contrib-salesforce#15]
In the soql and sosl nodes, if there's an issue with the connection it get's raised and caught by a Catch All node, but if there's an issue with the query the error isn't caught by the Catch All node. 

E.g.

- If I set the connection to "Add new connection-config" the error ("TypeError: Cannot read property 'callbackUrl' of null") will be raised and captured by a "Catch All" node. 
- If I put in a bad search query in to the sosl node the error (eg "No search term found. The search term must be enclosed in braces.")  isn't caught by the "Catch All" node, but it is written to the terminal window. 

![image](https://user-images.githubusercontent.com/8549444/36820373-847331d8-1cbb-11e8-8248-53f46dae3826.png)

**Comment by Stwissel** [comment]
Good catch, I'll see how we can fix that. Error needs to bubble up from the nforce library

**Comment by dwindibank** [comment]
As an FYI ... my intern was playing with this to see if there's an easy fix, and this isn't an issue if you switch to the main nforce library. So at some point the nForce library fixed this issue.

**Comment by dwindibank** [comment]
As a note:  same thing is happening with the DML node.  Fairly routine SF errors (such as the ones below) are not getting caught. 

Example errors not getting caught:
- Record Currently Unavailable: The record you are attempting to edit, or one of its related records, is currently being modified by another user. Please try again.
- invalid cross reference id
- bad value for restricted picklist field

**Comment by dwindibank** [comment]
Another related case for this ... Due to a problem with our VPN our Node-Red server can't access SalesForce. The error isn't being handled correctly (i.e. the node is just getting stuck with a status of "Connecting". 

This the the error from the logs:

`You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 136.147.43.44:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)`

The ECONNREFUSED error is actually coming from our VPN issue, but the Nodes are not catching the error.

**Comment by Stwissel** [comment]
Fixed in 0.7.0
