### ISSUE TITLE
Streaming Node - Duplicated msg(s) when passing to a function

### ISSUE THREAD

**Issue by judamarto** [Stwissel/node-red-contrib-salesforce#16]
It works fine when passing a streaming subscription to a debug node directly. 

However, for some reasons it duplicates msg(s) when adding a node "function" in between. 

<img width="980" alt="screen shot 2018-03-01 at 9 58 46 am" src="https://user-images.githubusercontent.com/1048402/36851435-32d3d5ea-1d37-11e8-869e-20838387f584.png">

<img width="1178" alt="screen shot 2018-03-01 at 9 58 20 am" src="https://user-images.githubusercontent.com/1048402/36851436-32e2339c-1d37-11e8-8102-eb515ef88ced.png">

**Comment by Stwissel** [comment]
Seems to be related to restarting NodeRED when redeploying flows? Thoughts?

**Comment by judamarto** [comment]
Yes, that what we notice - the duplicate msg(s) will correlate to how many times we click the deploy button. The PR I sent you was trying to resolve this issue - https://github.com/Stwissel/node-red-contrib-salesforce/pull/17

Please see my comment on the issue - https://github.com/Stwissel/node-red-contrib-salesforce/issues/16

**Comment by Stwissel** [comment]
Fixed in 0.7.0
