### ISSUE TITLE
Implement GET?

### ISSUE THREAD

**Issue by javaknight** [Stwissel/node-red-contrib-salesforce#18]
Looks like the functionality to fetch a node by record isnt there. eg the restful api allows you to

GET https://xxx.my.salesforce.com/services/data/v39.0/sobjects/Account/{sfidgoeshere} 

that should be a part of the DML node. very basic operation.

**Comment by Stwissel** [comment]
The DML node is output only. NodeRED design guidelines state a node should stick to one type. However a new Node e.g. `Fetch SF Object` could provide that functionality - PullRequest welcome. Until then you can use the SOQL node with a template (or function) node in front. The template node would take the Object Name and Object ID as input and render the SOQL to be passed to the SOQL node.
