### ISSUE TITLE
Allow user to pass environment (eg Sandbox, production, etc) via environment variable?

### ISSUE THREAD

**Issue by javaknight** [Stwissel/node-red-contrib-salesforce#20]
The current select box doesnt allow you to input an environment variable. other parts of the node can be configured by environment variable. can you extend it to allow the user to select environment via environment variable?

**Comment by Stwissel** [comment]
What would be the use case for that? Ease of deployment from/to Sandbox/Production?

**Comment by javaknight** [comment]
Yes. Right now, I have to make sure I meticulously switch each Salesforce node to the proper environment when I push and pull to/from github when developing between sandbox and publishing to production. It is pretty easy to make a mistake especially when you have larger flows that scroll right or down.

**Comment by Stwissel** [comment]
Switching to nforce8, added env parameter [ConnectionName]_Environment to define `production` or `sandbox` in v0.6
