### ISSUE TITLE
Can't pass credentials from msg object

### ISSUE THREAD

**Issue by mrpopodev** [Stwissel/node-red-contrib-salesforce#23]
I checked "Allow credentials in msg object" in connection-config node but it doesn't work.
At least code below has to be fixed.
soql.js　and 
line 22
` if (config.allowMsgCredentials && msg.hasOwnProperty("sf")){....}`
↓
` if (this.connection.allowMsgCredentials && msg.hasOwnProperty("sf")){....}`

sosl.js line 21 also needs to be fixed as well.

**Comment by Stwissel** [comment]
fixed in 0.6
