### ISSUE TITLE
Feature request: Set API version

### ISSUE THREAD

**Issue by dwindibank** [Stwissel/node-red-contrib-salesforce#27]
Currently the nforce library defaults the API version to 38. I needed something from the version 39 API. 

It looks like it would be easy to add a version the connection-config node, and then pass the value to the nforce library in the nforce_wrapper. 

I can get together a pull request, but I was wondering should it be a drop down or a number? Workbench has a drop down so that was my initial thought, but it might be a pain to have to add new values to the drop down 3 times a year.

**Comment by Stwissel** [comment]
I'm planning to update the library in lockstep with Salesforce releases soon. So the API number will point to the latest. Would you still want the number to be configurable?

**Comment by dwindibank** [comment]
> Would you still want the number to be configurable?

I can see a couple of scenarios where it would still be useful to be able to set the release number:

- Want to try new API in Sandbox before it's available in production
- Change in new API is breaking flow so want to set it to the old value 

Is node-red-contrib-salesforce switching to using nforce8?

**Comment by Stwissel** [comment]
Got it. Eventually I'll add an environment parameter. Using nforce8 is the plan. Quite some refactoring to do there. I'm upgading the packages and eventually swap out the http library for something promised based

**Comment by Stwissel** [comment]
added in 0.6. In config object
