### ISSUE TITLE
Cannot find module 'nforce' - Node-RED-Docker container

### ISSUE THREAD

**Issue by Frusty87** [Stwissel/node-red-contrib-salesforce#32]
I use node-red in a docker container.

I installed your plugin and after reload node-red I can see only one node under nodes. I see only “obm”. If I go to “Setting -> Palette -> Nodes” I see this Error messega under “node-red-contrib-salesforce” package: Error: Cannot find module 'nforce' (line:3)

I found in file package.json -> dependencies -> nforce8 ??? but in file “nforce_wrapper.js” will user nforce. Could this be the problem?

**Comment by Stwissel** [comment]
I’ll publish a new version soon. Sits in my dev branch. Thx for reporting

**Comment by dwindibank** [comment]
Any update? I installed node-red on a new server (0.20.2) and installed node-red-contrib-salesforce from the pallet and got the same error. Everything is a clean fresh install from NPM.  

It was pretty trivial to change nforce to nforce8 in two spots (nforce_wrapper.js and dml.js) and it seems to be working find now.

**Comment by Stwissel** [comment]
Fixed in 0.7.0 release
