### ISSUE TITLE
"Error: invalid or missing clientId"

### ISSUE THREAD

**Issue by romualdr** [Stwissel/node-red-contrib-salesforce#34]
Connection fails because nforce8 is waiting for "clientId" - but we are giving "consumerId" as parameter in `nforce_wrapper.js`.

I guess [this nforce8 commit](https://github.com/Stwissel/nforce8/commit/e898467214dae8cf319c02d0f6d42265066d7352#diff-168726dbe96b3ce427e7fedce31bb0bc) from 14 days ago broke the connection.

**Comment by AustinKf2** [comment]
I am also having this same issue when giving the credential information from a connected app.

**Comment by Stwissel** [comment]
Fixed in 0.7.0 release
