### ISSUE TITLE
This doesn't work with Node-red 1.0

### ISSUE THREAD

**Issue by ramoriusvt** [Stwissel/node-red-contrib-salesforce#44]
I'm not sure what the issue is, but I was trying to create a fresh node-red server (on 1.0.2) and it couldn't connect to SF. It was able to connect to other http services, just not Salesforce.

I ended up having to revert to node-red 0.20 and everything is working (as well as it was) again. At least it can connect.

Not having any logs of connectivity or feedback at all really makes this hard to troubleshoot.

Good luck to all!

**Comment by Stwissel** [comment]
Works with NodeRED 3.0.x now
